### ISSUE TITLE
nectar --example fails

### ISSUE THREAD

**Issue by unlight** [seraum/nectarjs#5]
NectarJS Client v0.0.46
Win8.1x64 
node v8.9.0
```
nectar --example
````
Fails with error:
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\My\Dev\nectarjs-playground\example\arduino.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at copyExample (C:\Users\Roman\AppData\Roaming\npm\node_modules\nectarjs\nectar.js:257:8)
    at Object.<anonymous> (C:\Users\Roman\AppData\Roaming\npm\node_modules\nectarjs\nectar.js:86:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

**Comment by FlorianBord2** [comment]
That work for me, on Window 10.
Have you more info about this error ? 
![nectar](https://user-images.githubusercontent.com/30652375/34111334-bbbe8f88-e409-11e7-8841-08a9e8f76e46.PNG)
